### ISSUE TITLE
Incompatible with file-6.0.0-nullsafety

### ISSUE THREAD

**Issue by CiriousJoker** [wiredashio/wiredash-sdk#97]
That dependency is a prerelease, but flutter_driver requires it.

```
dependency_overrides:
  file: 5.2.1
```

This workaround seems to at least get around the build errors. Haven't tried Flutter Driver yet.

**Comment by brianegan-wiredash** [comment]
Thanks for the report, mate! We've got a wider version range in place now, and we'll work on removing that dependency altogether.

**Comment by passsy** [comment]
Similar to #87 

This issue is already fixed. Please update to [`0.3.0`](https://github.com/wiredashio/wiredash-sdk/releases/tag/0.3.0)

**Comment by CiriousJoker** [comment]
I agree that it's a duplicate, sorry for not finding it when searching for similar issues. To be honest, my main goal was to share my quickfix.

This bug is still present in the latest published `wiredash 0.3.0` as well as the latest Flutter dev:

```
Flutter 1.24.0-6.0.pre • channel dev • https://github.com/flutter/flutter.git
Framework • revision 13896b3bd1 (5 days ago) • 2020-10-28 19:43:19 -0700
Engine • revision 073263e39d
Tools • Dart 2.11.0 (build 2.11.0-260.0.dev)
```

This error doesn't seem to be present in wiredash-sdk master, so I guess this can be closed on the next release.

**Comment by brianegan-wiredash** [comment]
It's a great idea to share that info, much appreciated :)

**Comment by passsy** [comment]
Released in v0.4.0
